### ISSUE TITLE
[FORMATTING/LAYOUT] dark mode

### ISSUE THREAD

**Issue by inpharmaticist** [AnonymousPlanet/thgtoa#15]
### Formatting/Layout Issue:

Option for dark mode? Would be nice for PDF.

**Comment by AnonymousPlanet** [comment]
I agree :) I'll try to get this for the next release 0.7.0.

**Comment by AnonymousPlanet** [comment]
Dark PDF has been added in v0.7.0. Website will follow in next releases.

**Comment by AnonymousPlanet** [comment]
Theme has been changed to dark for the whole site in v0.7.1
