### ISSUE TITLE
[FORMATTING/LAYOUT] Restore previous font

### ISSUE THREAD

**Issue by exv3** [AnonymousPlanet/thgtoa#16]
### Formatting/Layout Issue:

The new font might look cool and fancy but it's harder to read the contest right now, especially for people like me who have astigmatism. Please reconsider changing the font to the old one (Helvetica was it?) or the one that GitHub use in its README

**Helvetica**
![helvetica](https://user-images.githubusercontent.com/46762995/107413250-744c4d00-6b08-11eb-8c0b-cd5f654b70a5.png)

**Segoe_UI** (the most friendly and easy for eyes to read, used in GitHub README)
![segoe_ui](https://user-images.githubusercontent.com/46762995/107413282-7e6e4b80-6b08-11eb-919d-897f34caa96d.png)

**Comment by AnonymousPlanet** [comment]
Agreed :) Will do :)

**Comment by exv3** [comment]
Thanks :)

**Comment by AnonymousPlanet** [comment]
Fixed with Segoe UI as requested. Also changed spacing on the PDFs for better readability.
