### ISSUE TITLE
Translating guide to different language

### ISSUE THREAD

**Issue by Biocycle1** [AnonymousPlanet/thgtoa#2]
Is this possible to translate different languages?

**Comment by AnonymousPlanet** [comment]
I have no plans to do this myself but I'm welcoming any willing contributor to do this.

It's also open-source so you may fork it and translate it if you wish to do so.  

In the mean time, Google translate should do just fine for most of the guide.

**Comment by AnonymousPlanet** [comment]
I have no plans to do this myself but it's open-source and you can fork it and translate it into a new language if you wish to do so. I just don't think I'll be doing this within this repository as I would be unable to properly check the accuracy of any translation myself.

For now Google Translate should help you.

**Comment by AnonymousPlanet** [comment]
After further investigation, I can see Transifex and Weblate do offer some free plans for open-source projects. I'm re-opening this issue and investigating the option.

**Comment by AnonymousPlanet** [comment]
So Russian translation is being done by a contributor :) And Transifex system seems to be working just fine. If any other translator wants to translate to another language. Just say so in here.

**Comment by AnonymousPlanet** [comment]
This is now a work in progress :) Translation is now possible using Transifex. If you want to translate :) Feel free to ask me :) Closing
