### ISSUE TITLE
[LINK/REFERENCE] A link does not work on the main page

### ISSUE THREAD

**Issue by erenmenges** [AnonymousPlanet/thgtoa#20]
### Dead/Bad Link or Reference Issue:

In the main project's website, a link is faulty and it does not work, because it has two https markers.

![foto_no_exif](https://user-images.githubusercontent.com/76516591/111069633-04eac400-84df-11eb-8d17-ac0626459417.jpg)
(The latter)

> Online versions of the guide are available at:
GitHub: https://https://anonymousplanet.org/guide.html

**Comment by AnonymousPlanet** [comment]
Fixed :) Thank you for spotting it

**Comment by erenmenges** [comment]
No problem. By the way, the guide is amazing. Thank you for creating such a masterpiece.
