### ISSUE TITLE
Suggestion: Add tor-mirror into HTTP header 

### ISSUE THREAD

**Issue by senden9** [AnonymousPlanet/thgtoa#23]
Hi!

Sites can communicate to browsers that there is a tor-mirror of it using a special HTTP header. If a site do so the browser can suggest to switch to that mirror or switch automatically to that mirror (depending on client configuration). Instead of a HTTP-header also a `<meta>`-tag can be used. 

See the [official documentation](https://community.torproject.org/onion-services/advanced/onion-location/) or this [blog entry](https://www.ctrl.blog/entry/tor-onion-location-header.html) if you want to read more about it.

As this could help users and fit great to the topic of the guide. I suggest to add such a mechanism.

**Comment by AnonymousPlanet** [comment]
Good idea!

**Comment by AnonymousPlanet** [comment]
Merged
