### ISSUE TITLE
[NEW/MISSING INFO] ChaCha20 - File Encryption

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#36]
I was skimming through your guide and noticed this suggestion on the topic of "Bad Cryptology:"

> File/Disk Encryption:
> 
> Prefer: AES 256 Bits with HMAC-SHA-2 or HMAC-SHA-3 (This is what Veracrypt, Bitlocker, Filevault 2, KeepassXC, and LUKS use)
> 
> Avoid: Anything else

I found it weird that your site only recommends AES for File/Disk Encryption.

So I'm proposing the inclusion of ChaCha20 which has been use in TLS for Google and Cloudflare, [1](#1.) and for Mobile ARM chips without the AES instruction set, to be recommended on your site for File Encryption.

I won't be fully explaining why you would want to choose ChaCha20 over AES as that can be done researching on your own and I don't want to skew your view with my own, I will though provide a Crypto Stack Exchange [link](https://crypto.stackexchange.com/questions/34455/whats-the-appeal-of-using-chacha20-instead-of-aes) where they explain the appeal of ChaCha20 over AES and a few links and reasons to include ChaCha20.

If you don't want to click & read through the link:

1. Faster on CPU's without dedicated instruction sets for AES. [2](#2.)
2. AES is vulnerable to timing attacks whereas ChaCha20 is not vulnerable to such attacks. [3](#3.)

It also helps to have a backup cipher in case AES is ever broken (Highly unlikely)

I'd also like to note that ChaCha20 has a security margin than AES due to a greater number of rounds. [4](#4.)

I will say that I am by no means discrediting your guide or trying to say that AES is an inferior encryption algorithm to ChaCha20 (One is a block cipher and the latter is a stream cipher) I'm just opening this issue to help improve the site.

P.S I personally would recommend XChaCha20 instead of ChaCha20 due to the longer nouce. (192-bits)

# Sources

<a name="1."/> 1. Google & Cloudflare uses ChaCha20
https://security.googleblog.com/2019/02/introducing-adiantum-encryption-for.html
https://blog.cloudflare.com/it-takes-two-to-chacha-poly/	
https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography/

<a name="2."/> 2.  Explanation on why ChaCha20 is faster than AES (Top answer)
https://crypto.stackexchange.com/questions/34455/whats-the-appeal-of-using-chacha20-instead-of-aes

<a name="3."/> 3. Article of Cache-timing attacks on AES by Daniel Bernstein (Creator of ChaCha20)
https://cr.yp.to/antiforgery/cachetiming-20050414.pdf

<a name="4."/> 4. ChaCha20 security margin
https://eprint.iacr.org/2019/1492.pdf

# Additional Notes

Original Paper on ChaCha20 by Daniel Bernstein
https://cr.yp.to/chacha/chacha-20080128.pdf

RFC Document

Old
https://datatracker.ietf.org/doc/html/rfc7539

New
https://datatracker.ietf.org/doc/html/rfc8439

Wikipedia (Including a section on adoption)
https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant

**Comment by AnonymousPlanet** [comment]
Agreed and will add it for the next release. Thank you!

**Comment by AnonymousPlanet** [comment]
Oh and the reason why it wasn't included is simply because I was not aware of it and it's not really an option offered in the encryption software I commonly use. Nor the option most commonly proposed by the software I recommend.

**Comment by AnonymousPlanet** [comment]
Added

**Comment by SerpentSecurity32** [comment]
I see.

Shame since ChaCha20 was created by someone I really admire (Daniel J. Bernstein)

He fought with the US Government in court on the export of Cryptography which was an iconic case at the time and set out a pretty important precedent. [1](##1.)  The ruling ended up declaring that software was protected speech under the First Amendment. [2](##2.) The case was even cited by Apple in the FBI–Apple encryption dispute (Otherwise known as The San Bernardino iPhone case) which was another very important case on Cryptography.  [3](##3.)

Check out his other work and his articles if ever you're curious about Cryptography and how it functions.

# Sources

<a name="#1."/> 1. Bernstein v. United States

https://en.wikipedia.org/wiki/Bernstein_v._United_States

https://www.eff.org/cases/bernstein-v-us-dept-justice

<a name="#2."/> 2. Software is protected speech

https://www.eff.org/deeplinks/2015/04/remembering-case-established-code-speech

<a name="#3."/> 3. Apple citing Bernstein's case

https://www.wired.com/2016/02/apple-brief-fbi-response-iphone/

# Additional Notes

Wikipedia, Daniel J. Bernstein
https://en.wikipedia.org/wiki/Daniel_Bernstein

Wikipedia, FBI–Apple_encryption_dispute
https://en.wikipedia.org/wiki/FBI–Apple_encryption_disput

**Comment by AnonymousPlanet** [comment]
Thankfully this is no longer an issue at least with AES (but only few people know AES was not developed by and for the US military and was just made by two researchers in Belgium).

**Comment by SerpentSecurity32** [comment]
Note: While ChaCha20 is indeed faster than AES on chips which do not have the AES instruction set, pretty much 99% of modern X86 chips and Mobile ARM chips support the AES instruction set.

11+ years for Intel's X86 chipset [1](###1.) and 6+ years for Snapdragon's Mobile ARM chipset [2](###2.) as of the time I'm posting this. 

In the future with the possible rise of ARM / RISC-V architectures (As can be seen with the Apple M1) we could see a surge of new ARM / RISC-V CPUs which do not support the AES instruction set; In cases like this ChaCha20 can be used as an alternative to AES so as to not have slow speeds.

ChaCha20 can also be used for older Mobile Devices which chipset do not support the AES instruction set (Snapdragon 801 and lower) [3.](###3.) (No source)

# Sources

<a name="##1."/> 1. Intel AES instruction set https://software.intel.com/content/www/us/en/develop/articles/intel-advanced-encryption-standard-instructions-aes-ni.html

<a name="##2."/> 2. Snapdragon is FIPS 140-2 certified https://www.qualcomm.com/news/onq/2014/11/07/cryptographic-module-snapdragon-805-fips-140-2-certified

<a name="##3."/> 3. No source besides Qualcomm saying the Snapdragon 805 was FIPS 140-2 certified while nothing of the sort was said for the Snapdragon 801

# Additional Notes

Wikipedia AES instruction set

https://en.wikipedia.org/wiki/AES_instruction_set

**Comment by AnonymousPlanet** [comment]
You should consider joining the Modern Crypto room on Matrix https://matrix.to/#/#moderncrypto:gnuradio.org

You might have interesting discussions there (I'm in there too)

**Comment by SerpentSecurity32** [comment]
> Thankfully this is no longer an issue at least with AES (but only few people know AES was not developed by and for the US military and was just made by two researchers in Belgium).

Funny thing is those two researchers in Belgium were nobodys compared to rest of those who participated in the AES competition and now their submission is used on every PC around the globe. Really amazing if you think about it. ;)

**Comment by SerpentSecurity32** [comment]
> 
> 
> You should consider joining the Modern Crypto room on Matrix https://matrix.to/#/#moderncrypto:gnuradio.org
> 
> You might have interesting discussions there (I'm in there too)

I was thinking of creating a Matrix account in the next coming weeks; Now I have 1 more server to consider joining. Thanks for the help!

**Comment by AnonymousPlanet** [comment]
Nah you don't :) It's a federated room :) you can join it from a matrix.org account or any other federated homeserver account

**Comment by SerpentSecurity32** [comment]
Wait. I do not seem to understand.
I do not yet have a matrix.org account or any other federated homeserver account. Which I am planning to create in the next couple of weeks.

I understand that it is federated and that I don't have to create a new account for every server but I do not have an account for the Matrix Protocol itself.

**Comment by SerpentSecurity32** [comment]
Another note: Daniel Bernstein the creator of ChaCha20 is quoted on the Qubes OS website.

https://www.qubes-os.org/

**Comment by AnonyPla** [comment]
FYI the silly rule was removed. I sent you an apology and invited you back. Apologies again.
