### ISSUE TITLE
[INCORRECT INFORMATION] Changelog | Added ChaCha2

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#37]
> v0.9.9c
> 
> Improved the password/passphrase recommendation section
> Added a new Tor Exit node to the project https://metrics.torproject.org/rs.html#details/F535BA067A776457083141688C7FE781B6DFB24E
> Added CHACHA2 to the recommended file/disk encryption algorithms

https://anonymousplanet.org/CHANGELOG.html
http://thgtoa7imksbg7rit4grgijl2ef6kc7b56bp56pmtta4g354lydlzkqd.onion/CHANGELOG.html

**Comment by AnonymousPlanet** [comment]
Yes this was already fixed I saw the typo while updating
