### ISSUE TITLE
[INCORRECT INFORMATION] Possible typos

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#38]
> Setup a safe Browser within Qube OS (optional but recommended):

Was called Qubes OS previously unless you are referring to qubes which is what Qubes OS calls an isolated compartment but then there's no need to add an OS to the end of it. I would also like to add that it's called qubes/qube (Non capitalized) [1](#1.)

> TAILS

I am aware that Tails is an acronym but the official website calls it "Tails" rather than "TAILS". [2](#2.)
Tor for example is Tor and not TOR. [3](#3.) If I'm correct this is due to copyright and trademark purposes.

Confusing I know.

Sources

<a name="1."/> 1. Qubes OS website calling them qubes/qube (Non capitalized)
https://www.qubes-os.org/intro/
https://www.qubes-os.org/doc/glossary#qube

<a name="2."/> 2. Official Tails/TAILS Website
https://tails.boum.org/

<a name="3."/> 3. Official Tor Project Twitter Account tweeting "It's Tor, not TOR. Pass it on."
https://twitter.com/torproject/status/1374035642078797827
https://nitter.fdn.fr/torproject/status/1374035642078797827

**Comment by AnonymousPlanet** [comment]
You're absolutely right. Will be fixed in next release. Thank you. 

TAILS will be changed to Tails.

Qube OS is a typo and will be changed to Qubes OS. 

But I don't see any TOR uppercase only anywhere. It's Tor everywhere.

**Comment by AnonymousPlanet** [comment]
Fixed in 0.9.9d

**Comment by SerpentSecurity32** [comment]
Woops. My bad I meant to use Tor to compare how they also don't capitalize their name despite it being an acronym.  Not that you capitatized Tor in your site. Sorry for any wasted time.

**Comment by AnonymousPlanet** [comment]
It's okay you were right for Qube and TAILS

**Comment by AnonymousPlanet** [comment]
Any help is appreciated

**Comment by SerpentSecurity32** [comment]
Just realized I used the Incorrect Information tag rather than the Grammar/Spelling Issue -_-

The irony is not lost on me.
