### ISSUE TITLE
[NEW/MISSING INFO] Add Brave ad-blocking source

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#39]
Currently the Brave section in Appendix V does not have a source for it's ad-blocking

Brave ad-blocking source

https://support.brave.com/hc/en-us/articles/360022973471-What-is-Shields

**Comment by AnonyPla** [comment]
That it's a fork of uBlock you mean?

**Comment by AnonyPla** [comment]
done :-)
