### ISSUE TITLE
[NEW/MISSING INFO] Section on recommended search engines

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#40]
You recommend DuckDuckGo and StartPage on the site so I thought why not have a dedicated section on recommended search engines?

If you wanted you could just link to PrivacyTools' recommended Search Engine list and leave it at that.

PrivacyTools Search Engine list
https://privacytools.io/providers/search-engines
Onion site for Tor Users
http://www.privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion/providers/search-engines/

Any thoughts?

P.S I recommend self-hosting a Searx instance on your own Dedicated Server/VPS. You could also add Searx to the list and link to your recommended VPS Providers.

**Comment by AnonyPla** [comment]
You're right :) I'll add a reference to PTIO

**Comment by AnonyPla** [comment]
I added one :)
