### ISSUE TITLE
[NEW/MISSING INFO] Add explanation of sources to beginning of the guide

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#41]
Currently the Guide doesn't explain that the little numbers to the end of a statement links to the source. (Correct me if I'm wrong as I only noticed this till now and my eyes are tired as I'm fact checking this)

Also would like to add a sources section to the Table of Contents, if you go to the end of the guide the Monero disclaimer and sources list aren't properly separated. (Image provided, apologies for image quality)

https://ibb.co/71NDkY5

**Comment by AnonyPla** [comment]
Yeah the separation is there in the PDFs and source document but not in the Markdown but I agree I should add a separation between both and a TOC entry

**Comment by AnonyPla** [comment]
I don't think an "explanation" that the numbers = references is needed.

I added a separator and a "References" in the ToC

**Comment by SerpentSecurity32** [comment]
In retrospect having the clarification that the numbers = references I agree might be unneeded since most people are used to it due to Wikipedia having the same format so I'm fine with that too.
