### ISSUE TITLE
[SPELLING/GRAMMAR] Homepage Typos / Grammar

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#42]
Second sentence doesn't have a space separating it from the first sentence. It also combines an exclamation mark and a full stop.

> legally.It is written with hope for activists, journalists, scientists, lawyers, whistle-blowers, and good people being oppressed/censored anywhere!.

The last sentence has a minus sign in between pre and requisite which is incorrect. [Source](https://www.merriam-webster.com/dictionary/prerequisite)

> No pre-requisites besides English reading are required. 

Also not sure if "English reading" is correct grammar I would change it instead to something like this.

> No prerequisites besides basic knowledge of English are required.

Although I'm not sure whether some of the English included in the guide can be called "basic"

I would also add the requirement for "basic knowledge of technology and common acronyms"

> No prerequisites besides basic knowledge of English and technology and common acronyms regarding technology"

Also wondering if the homepage is included in the GitHub repository since I wasn't able to find it.

**Comment by AnonyPla** [comment]
The homepage is the README file in the repository.

I agree with your fixes.

**Comment by AnonyPla** [comment]
Fixed!

**Comment by AnonyPla** [comment]
Btw if you see more issues :) Don't hesitate to fork and make a pull request !
