### ISSUE TITLE
[NEW/MISSING INFO] Blake2 - Hashes

### ISSUE THREAD

**Issue by SerpentSecurity32** [AnonymousPlanet/thgtoa#53]
I was skimming through your guide and noticed this suggestion on the topic of "Bad Cryptography"

> Hashes:
>
> Prefer: SHA256 (widely used), SHA512 (preferred), or SHA-3
>
> Avoid: SHA-1, SHA-2, MD5 (unfortunately sill widely used, CRC, MD6 (rarely used)

I found it weird that your site recommends SHA2 for Hashing. So I'm proposing the inclusion of Blake2 which has seen use in projects such as Argon2 (Which you recommend for Password Storage), Wireguard, any more projects.

BLAKE2 is a cryptographic hash function based on BLAKE, which was a SHA3 Finalist.

> BLAKE2 is a cryptographic hash function faster than MD5, SHA-1, SHA-2, and SHA-3, yet is at least as secure as the latest standard SHA-3. (Blake2.net)

![skylake](https://user-images.githubusercontent.com/87622726/130365432-7293684c-208b-4ee5-895d-b6250207a05d.jpg)

Tested on a Skylake Intel CPU. Plot taken from Blake2.net.

## Reasons to use Blake2 over SHA2

1. Faster speeds as can be seen in the plot above.

2. SHA2 is vulnerable to length-extension whereas Blake2 is not susceptible to length-extension.

3. Higher security margin.

***

I will also note that the note that the likely reason Keccak (Currently SHA3) won the SHA3 competition instead of BLAKE is BLAKE's similarity to SHA-2

> The main reason that NIST gave was that BLAKE was more similar to SHA-2 than Keccak was. When the SHA-3 contest was designed, the whole point of it was to provide a new hash function that would be ready in case SHA-2 got broken, so it made sense to require the winner to be different from SHA-2. However now, with almost a decade more of research and SHA-2 looking no weaker, a hash function being similar to SHA-2 doesn't seem bad, and might even be good. (crypto.stackexchange.com/questions/31674)

**P.S** I suggest separating Blake2b and Blake2s as Blake2b is for 64 bit platforms and Blake2s is for 8-32 bit platforms.

## Links

Blake2 PDF https://www.blake2.net/blake2.pdf

RFC 7693 https://tools.ietf.org/html/rfc7693

Blake2.net (Official Website) https://www.blake2.net

Wikipedia https://en.wikipedia.org/wiki/BLAKE_%28hash_function%29#BLAKE2

Additional Notes

What advantages does Keccak/SHA-3 have over BLAKE2? https://crypto.stackexchange.com/questions/31674/what-advantages-does-keccak-sha-3-have-over-blake2

**Comment by AnonyPla** [comment]
Done
