### ISSUE TITLE
[LINK/REFERENCE] Various broken links including one that contains a Windows path. 

### ISSUE THREAD

**Issue by operator-name** [AnonymousPlanet/thgtoa#6]
### Dead/Bad Link or Reference Issue:

There are a decent amount of dead or broken links in the document. Should be easy to find by regex searching [.*] on the markdown output. 

There's quite an egregious one (in two places) that can be found searching for `C:\`

**Comment by AnonymousPlanet** [comment]
Fixed :) Thank you :)
