### ISSUE TITLE
[INCORRECT INFORMATION] Remove all mentions of Privacy Badger

### ISSUE THREAD

**Issue by NSABackdoors** [AnonymousPlanet/thgtoa#68]
### Incorrect Information:
uBO with default lists is better than PB (trained or not)

https://teddit.net/r/uBlockOrigin/comments/k6cezt/discussion_is_it_advisable_to_use_privacy_badger/gem3yds

https://teddit.net/r/firefox/comments/o28yi4/ghostery_on_firefox/h26mguk

There have also been cases of PB causing problems with uBO

https://teddit.net/r/uBlockOrigin/comments/pmqxh8/adblocker_detected/

**Comment by AnonyPla** [comment]
Reviewing your data

**Comment by AnonyPla** [comment]
Agreed, will remove in next release
