### ISSUE TITLE
[INCORRECT INFORMATION] Discord & Captchas

### ISSUE THREAD

**Issue by bptato** [AnonymousPlanet/thgtoa#7]
https://anonymousplanet.github.io/thgtoa/guide.html#overview states that Discord doesn't make you solve captchas and requires no phone number - see conflicting information on both points on opal's [blog post](http://wowana.me/blog/guess-im-done-with-discord.xht).

I also have to struggle with reCAPTCHA for like ten minutes on average every time I try to log in to Discord with the Tor Browser, so I'm quite surprised you haven't experienced that. Is it more tolerant towards Brave?

**Comment by AnonymousPlanet** [comment]
Well there are few points here: 

- Yes it's more tolerant to Brave over Tor than Tor Browser
- I was using the Discord client itself and not the Discord Website which is again more tolerant
- I recommend using an anonymous cash-paid VPN over Tor to mitigate the captcha issues (therefore not using Tor Browser but a normal Browser (preferably Brave with all the adblocking features and eventurally Ublock over Firefox)

If you're just using Tor Browser (or just Tor Browser from TAILS), you will experience issue. This is the reason I recommend Brave over Tor but also using a VPN over tor. It's the only way you'll be able to not have dozens of captchas to solve.

Nevertheless I will add some notes about this in the discord section. Thank you.

**Comment by AnonymousPlanet** [comment]
Fixed in next release. Thank you.
